// Alle Kloester aus der Liste vom 15.08.2026.
//
// Das Keyvisual zieht bei jedem Wuerfeln einen zufaelligen Eintrag daraus
// und schreibt ihn neben den Kreis.
//
// Die Nummer steht NICHT in den Daten: sie ergibt sich aus der Position in
// der Liste (erster Eintrag = 1). So ist die Nummerierung immer luecken-
// und doppellos, auch wenn spaeter ein Kloster dazwischenkommt.
//
// Ein Eintrag besteht aus:
//   name  - wie das Kloster heisst
//   ort   - Ort und Kantonskuerzel
//   orden - der Orden, falls bekannt. Sonst weglassen oder "" lassen.

const KLOESTER = [
  { name: "Kloster St. Gallen / Klosterplan / Reichenau", ort: "St. Gallen, SG", orden: "Benediktiner" },
  { name: "Kapuzinerkloster Rapperswil", ort: "Rapperswil, SG", orden: "" },
  { name: "Klosterberg Sion", ort: "Uetliburg, SG", orden: "" },
  { name: "Kloster Wurmsbach", ort: "Rapperswil-Jona, SG", orden: "Zisterzienserinnen" },
  { name: "Propstei Alt St. Johann", ort: "Alt St. Johann, SG", orden: "" },
  { name: "Kapuzinerinnenkloster Maria Hilf", ort: "Altstätten, SG", orden: "Kapuzinerinnen" },
  { name: "Klostergarten im Kloster Magdenau", ort: "Magdenau, SG", orden: "Zisterzienserinnen" },
  { name: "Kapuzinerkloster Mels", ort: "Mels, SG", orden: "Kapuziner" },
  { name: "Kapuzinerinnenkloster Mariahilf", ort: "Steig, SG", orden: "Kapuzinerinnen" },
  { name: "Kloster Wurmsbach", ort: "Wurmsbach, SG", orden: "" },
  { name: "Kloster St. Scholastika", ort: "Tübach, SG", orden: "Kapuzinerinnen" },
  { name: "Kloster St. Georgen", ort: "Thurgau", orden: "" },
  { name: "Kloster Fischingen", ort: "Fischingen, TG", orden: "" },
  { name: "Klösterli", ort: "Frauenfeld, TG", orden: "" },
  { name: "Kartause Ittingen", ort: "Ittingen, TG", orden: "" },
  { name: "Kloster Werd", ort: "Werd, TG", orden: "" },
  { name: "Kloster Allerheiligen", ort: "Schaffhausen, SH", orden: "" },
  { name: "Kloster Maria der Engel", ort: "Appenzell", orden: "" },
  { name: "Kloster Leiden Christi", ort: "Jakobsbad, AI", orden: "Kapuzinerinnen" },
  { name: "Maria Rosengarten Wonnenstein", ort: "Niederteufen, AI", orden: "" },
  { name: "Kloster St. Ottilia", ort: "Walzenhausen, AR", orden: "Kapuzinerinnen" },
  { name: "Kloster Wettingen / Stella Maris", ort: "Wettingen, AG", orden: "" },
  { name: "Kloster Fahr", ort: "Würenlos/Fahr, AG", orden: "Benediktinerinnen" },
  { name: "Kloster Muri", ort: "Muri, AG", orden: "" },
  { name: "Kloster Hermetschwil", ort: "Hermetschwil, AG", orden: "" },
  { name: "Kloster Königsfelden", ort: "Windisch/Königsfelden, AG", orden: "" },
  { name: "Klostergarten Gnadendal", ort: "Gnadenthal/Niederwil, AG", orden: "" },
  { name: "Krankenheim", ort: "Moderwil, AG", orden: "" },
  { name: "Kloster Kappel am Albis", ort: "Kappel am Albis, ZH", orden: "" },
  { name: "Kloster Rheinau", ort: "Rheinau, ZH", orden: "" },
  { name: "Kloster Rüeggisberg", ort: "Rüeggisberg, BE", orden: "" },
  { name: "Kloster Bellelay", ort: "Bellelay, BE", orden: "" },
  { name: "Kloster Frienisberg", ort: "Seedorf, BE", orden: "Zisterzienser" },
  { name: "Klostergarten St. Petersinsel", ort: "St. Petersinsel, BE", orden: "Cluniazenser" },
  { name: "Kloster Klingental", ort: "Basel, BS", orden: "" },
  { name: "Kloster Schöntal", ort: "Langenbruck/Schöntal, BL", orden: "" },
  { name: "Kloster Mariastein", ort: "Mariastein, SO", orden: "" },
  { name: "Kloster Dornach", ort: "Dornach, SO", orden: "Kapuziner" },
  { name: "Orthodoxes Kloster Beinwil", ort: "Beinwil, SO", orden: "" },
  { name: "Kapuzinerkloster Solothurn", ort: "Solothurn, SO", orden: "Kapuziner" },
  { name: "Ehem. Kapuzinerkloster Olten", ort: "Olten, SO", orden: "Kapuziner" },
  { name: "Kloster Namen Jesu", ort: "Solothurn, SO", orden: "" },
  { name: "Frauenkloster Nominis Jesu", ort: "Solothurn, SO", orden: "Tertiärkapuzinerinnen" },
  { name: "Kloster Lucelle / Lützel", ort: "Lucelle/Lützel, JU", orden: "Zisterzienser" },
  { name: "Chartreuse de La Lance", ort: "Concise, VD", orden: "Kartäuser" },
  { name: "Abbatiale Payerne / jardin imaginaire", ort: "Payerne, VD", orden: "" },
  { name: "Cour Catholique", ort: "Boncourt", orden: "" },
  { name: "Grandchamp", ort: "Boudry", orden: "" },
  { name: "Le Prieuré St. Pierre", ort: "Môtiers, NE", orden: "Benediktiner" },
  { name: "Abbaye d’Hauterive", ort: "Hauterive, FR", orden: "Zisterzienser" },
  { name: "Albertinum, Académie", ort: "Freiburg, FR", orden: "" },
  { name: "Kloster Bulle, Grünere", ort: "Bulle, FR", orden: "Kapuziner" },
  { name: "Couvent de Capucins", ort: "Freiburg, FR", orden: "Kapuziner" },
  { name: "Couvent de la Visitation", ort: "Freiburg, FR", orden: "" },
  { name: "Couvent de Cordeliers", ort: "Freiburg, FR", orden: "Franziskaner" },
  { name: "Couvent de Montorges", ort: "Freiburg, FR", orden: "" },
  { name: "Maison provinciale des Filles de la Charité", ort: "Freiburg, FR", orden: "" },
  { name: "Monastère de Maigrauge", ort: "Freiburg, FR", orden: "" },
  { name: "Couvent des Ursulines", ort: "Freiburg, FR", orden: "" },
  { name: "Couvent", ort: "Murten, FR", orden: "" },
  { name: "Couvent des capucins et chapelle N-D de", ort: "Bulle, FR", orden: "" },
  { name: "Couvent du Carmel", ort: "La Pâquier", orden: "" },
  { name: "Château d’En Haut", ort: "Orsonnens", orden: "" },
  { name: "Klostergarten Kartause La Valsainte", ort: "La Valsainte, FR", orden: "" },
  { name: "Ancienne chartreuse de la Part-Dieu", ort: "Gruyère, FR", orden: "" },
  { name: "Klostergarten in Estavayer-le-Lac", ort: "Estavayer-le-Lac, FR", orden: "Dominikanerinnen" },
  { name: "Abbaye de la Maigrauge", ort: "Freiburg, FR", orden: "Zisterzienserinnen" },
  { name: "Monastère du Carmel du Pâquier", ort: "Le Pâquier, FR", orden: "Karmeliterinnen" },
  { name: "Monastère Notre-Dame de Fatima", ort: "Freiburg, FR", orden: "Zisterzienserinnen" },
  { name: "Franziskanerkloster Mariaburg", ort: "Näfels, GL", orden: "Franziskaner" },
  { name: "Kloster Einsiedeln", ort: "Einsiedeln, SZ", orden: "Benediktiner" },
  { name: "Kapuziner-/Kapuzinerinnenklöster Schwyz", ort: "Schwyz, SZ", orden: "Kapuziner" },
  { name: "Klosterlein St. Joseph im Loo", ort: "Schwyz, SZ", orden: "" },
  { name: "Kloster", ort: "Arth, SZ", orden: "Kapuziner" },
  { name: "Kloster Au", ort: "Au, SZ", orden: "Benediktinerinnen" },
  { name: "Ingenbohl", ort: "Brunnen, SZ", orden: "Ingenbohl Schwestern" },
  { name: "Kloster St. Josef", ort: "Muotathal, SZ", orden: "Franziskanerinnen" },
  { name: "Kloster Mariahilf auf dem Gubel", ort: "Menzingen/Gubel, ZG", orden: "" },
  { name: "Kloster Heiligkreuz", ort: "Cham, ZG", orden: "" },
  { name: "Kloster Frauenthal", ort: "Frauenthal, ZG", orden: "Zisterzienserinnen" },
  { name: "Kloster Maria Opferung", ort: "Zug, ZG", orden: "" },
  { name: "Kloster Maria-Rickenbach", ort: "Maria-Rickenbach, NW", orden: "" },
  { name: "Kloster St. Klara", ort: "Stans, NW", orden: "" },
  { name: "Culinarium Alpinum", ort: "Stans, NW", orden: "Kapuziner" },
  { name: "Kloster Engelberg", ort: "Engelberg, OW", orden: "Benediktiner" },
  { name: "Kloster Melchtal", ort: "Melchtal/Kerns, OW", orden: "Benediktinerinnen" },
  { name: "Kloster St. Andreas", ort: "Sarnen, OW", orden: "" },
  { name: "Kulturkloster Altdorf", ort: "Altdorf, UR", orden: "" },
  { name: "Kloster Seedorf, St. Lazarus", ort: "Seedorf, UR", orden: "" },
  { name: "Stella Matutina", ort: "Hertenstein, LU", orden: "" },
  { name: "Kloster Baldegg", ort: "Baldegg, LU", orden: "" },
  { name: "Naturkloster / Comm Care", ort: "Luzern, LU", orden: "" },
  { name: "Kloster Eschenbach", ort: "Eschenbach, LU", orden: "" },
  { name: "Kapuzinerkloster Wesemlin", ort: "Luzern, LU", orden: "Kapuziner" },
  { name: "Kloster Gerlisberg", ort: "Luzern, LU", orden: "" },
  { name: "Mariahilf", ort: "Luzern, LU", orden: "" },
  { name: "Kloster Rathausen", ort: "Rathausen, LU", orden: "" },
  { name: "Ehem. Kapuzinerkloster Sursee", ort: "Sursee, LU", orden: "Kapuziner" },
  { name: "Kapuzinerinnen-Kloster St. Anna", ort: "Luzern, LU", orden: "Kapuzinerinnen" },
  { name: "Franziskanerkirche Luzern", ort: "Luzern, LU", orden: "Franziskaner" },
  { name: "Stiftung Felsentor", ort: "Weggis (Rigi), LU", orden: "Interreligiöses Zentrum" },
  { name: "Kapuzinerkloster Schüpfheim", ort: "Schüpfheim, LU", orden: "Kapuziner" },
  { name: "Giardino Convento della Santissima", ort: "Lugano, TI", orden: "" },
  { name: "Giardino Convento S. Giuseppe", ort: "Lugano, TI", orden: "Klarissinnen" },
  { name: "Kloster (Ortsteil Loreto)", ort: "Lugano, TI", orden: "" },
  { name: "Convento di Santa Maria dei Frati Cappuccini", ort: "Bigorio, TI", orden: "Kapuziner" },
  { name: "Ex Convento", ort: "Cugnasco, TI", orden: "" },
  { name: "Cortile de Convento della Malanotte", ort: "Monteggio", orden: "" },
  { name: "Monastero di Santa Maria Assunta", ort: "Claro, TI", orden: "" },
  { name: "Monastero Carmelitane Scalze", ort: "Tessin", orden: "Karmeliterinnen" },
  { name: "Monastero delle Cappuccine di San Giuseppe", ort: "Tessin", orden: "Kapuzinerinnen" },
  { name: "Lieu dit La Lance/La Chauvellaz", ort: "Concise, VD", orden: "Kartäuser" },
  { name: "Abbaye de Saint-Maurice", ort: "Saint-Maurice, VS", orden: "" },
  { name: "Abbaye Saint-Benoît de Port-Valais", ort: "Port-Valais, VS", orden: "" },
  { name: "Kloster St. Ursula", ort: "Brig, VS", orden: "" },
  { name: "Monastère de Géronde", ort: "Sierre, VS", orden: "" },
  { name: "Kloster", ort: "Bagnes", orden: "" },
  { name: "Kloster St. Johann Müstair", ort: "Müstair, GR", orden: "" },
  { name: "Kloster Disentis", ort: "Disentis, GR", orden: "" },
  { name: "Kloster Cazis", ort: "Cazis, GR", orden: "Dominikanerinnen" },
];
